version: '2'
services:
  php:
    build: docker/php
    #image: yiisoftware/yii2-php:7.4-apache
    container_name: gajin
    volumes:
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mysql
    container_name: gajin_mysql
    restart: always
    ports:
      - '3311:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gajin
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    volumes:
      - ./db_data4:/var/lib/mysql
