version: '2'
services:
  web:
    #build: docker/php
    image: yiisoftware/yii2-php:7.4-apache
    container_name: gaijin
    volumes:
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mysql
    container_name: gaijin_mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gaijin
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    volumes:
      - ./db_data:/var/lib/mysql
